language: ruby
rvm:
  - 2.1.3
addons:
  code_climate:
    repo_token:
      secure: "Kk01Cs/9oDRKwP6/FCNS1RWb+tDrvb39wTQoFE+Y241gO1zKzP/VTkzDnZsT50PfzhXCqYeVJOM/Gvdki5HPWnL6cErNiCcF3iAcUmu8iRIz4Ob8iwsxM2hNZJpcMW13XrycGmimXULnUaHYBEj4YtasKFueYwO9Daq6AS1eSGA="
